# https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html

#
# Base definition
#
name = "base-image"
description = "Base Image"
version = "2023.03.13"
distro = "rhel-87"

#
# Boot parameters
#
[customizations.kernel]
append = "net.ifnames.prefix=net quiet systemd.show_status=yes"

#
# Filesystem
#
[[customizations.filesystem]]
mountpoint = "/boot"
size = "1 GiB"
#[[customizations.filesystem]]
#mountpoint = "swap"
#size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/"
size = "8 GiB"
[[customizations.filesystem]]
mountpoint = "/home"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/tmp"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var"
size = "8 GiB"
[[customizations.filesystem]]
mountpoint = "/var/log"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = "2 GiB"

#
# Locale
#
[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "fi"

#
# Timezone
#
[customizations.timezone]
timezone = "Europe/Helsinki"
ntpservers = ["time.cloudflare.com"]

#
# Services
#
[customizations.services]
enabled = ["sshd", "tuned"]

#
# Firewall
#
[customizations.firewall.services]
enabled = ["ssh"]

#
# Packages
#
[[packages]]
name = "bash-completion"
version = "*"
[[packages]]
name = "bind-utils"
version = "*"
[[packages]]
name = "firewalld"
version = "*"
[[packages]]
name = "glibc-langpack-en"
version = "*"
[[packages]]
name = "glibc-minimal-langpack"
version = "*"
[[packages]]
name = "man-pages"
version = "*"
[[packages]]
name = "nano"
version = "*"
#[[packages]]
#name = "NetworkManager-config-server"
#version = "*"
## https://bugzilla.redhat.com/show_bug.cgi?id=2041424
#[[packages]]
#name = "perl-File-Temp"
#version = "*"
[[packages]]
name = "python3"
version = "*"
[[packages]]
name = "setools-console"
version = "*"
#[[packages]]
#name = "unzip"
#version = "*"
#[[packages]]
#name = "vim-enhanced"
#version = "*"

#
# Security compliance
#
#[customizations.openscap]
#datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
#profile_id = "xccdf_org.ssgproject.content_profile_cis_server_l1"

#
# Root
#
[[customizations.sshkey]]
user = "root"
key = "ssh-rsa changeme"

#
# User
#
[[customizations.user]]
name = "admin"
description = "Admin User"
#password = "$6$x..."
key = "ssh-rsa changeme"
home = "/home/admin"
shell = "/bin/bash"
groups = ["wheel"]
uid = 4444
