# https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html

#
# Base definition
#
name = "base-image"
description = "Base Image"
version = "2022.01.24"
distro = "rhel-85"

#
# Boot parameters
#
[customizations.kernel]
append = "net.ifnames.prefix=net ipv6.disable=0 quiet systemd.show_status=yes"

#
# Filesystem
#
##[[customizations.filesystem]]
### See: https://bugzilla.redhat.com/show_bug.cgi?id=2023796
##mountpoint = "/boot"
### 1G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
##size = 1073741824
##[[customizations.filesystem]]
### See: https://bugzilla.redhat.com/show_bug.cgi?id=2023796
##mountpoint = "swap"
### 2G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
##size = 2147483648
##[[customizations.filesystem]]
##mountpoint = "/"
### 8G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
##size = 8589934592
#[[customizations.filesystem]]
#mountpoint = "/home"
## 1G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
#size = 1073741824
##[[customizations.filesystem]]
### See: https://bugzilla.redhat.com/show_bug.cgi?id=2023796
##mountpoint = "/tmp"
### 1G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
##size = 1073741824
#[[customizations.filesystem]]
#mountpoint = "/var"
## 8G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
#size = 8589934592
#[[customizations.filesystem]]
#mountpoint = "/var/log"
## 2G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
#size = 2147483648
#[[customizations.filesystem]]
#mountpoint = "/var/log/audit"
## 1G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
#size = 1073741824
#[[customizations.filesystem]]
#mountpoint = "/var/tmp"
## 1G - https://bugzilla.redhat.com/show_bug.cgi?id=2023635
#size = 1073741824

#
# Locale
#
[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "fi"

#
# Timezone
#
[customizations.timezone]
timezone = "Europe/Helsinki"
ntpservers = ["time.cloudflare.com"]

#
# Services
#
[customizations.services]
enabled = ["sshd", "tuned"]

#
# Firewall
#
[customizations.firewall.services]
enabled = ["ssh"]

#
# Packages
#
[[packages]]
name = "bash-completion"
version = "*"
[[packages]]
name = "bzip2"
version = "*"
#[[packages]]
#name = "cloud-init"
#version = "*"
#[[packages]]
#name = "cloud-utils-growpart"
#version = "*"
[[packages]]
name = "firewalld"
version = "*"
#[[packages]]
#name = "insights-client"
#version = "*"
[[packages]]
name = "man-pages"
version = "*"
[[packages]]
name = "nano"
version = "*"
[[packages]]
name = "policycoreutils-python-utils"
version = "*"
[[packages]]
name = "prefixdevname"
version = "*"
[[packages]]
name = "psmisc"
version = "*"
[[packages]]
name = "python3"
version = "*"
[[packages]]
name = "python3-libselinux"
version = "*"
[[packages]]
name = "setools-console"
version = "*"
[[packages]]
name = "tar"
version = "*"
[[packages]]
name = "tuned"
version = "*"
[[packages]]
name = "vim-enhanced"
version = "*"
[[packages]]
name = "yum-utils"
version = "*"

#
# Security compliance
#
#[[packages]]
#name = "aide"
#version = "*"
#[[packages]]
#name = "openscap"
#version = "*"
#[[packages]]
#name = "openscap-scanner"
#version = "*"
#[[packages]]
#name = "scap-security-guide"
#version = "*"

#
# Root
#
[[customizations.sshkey]]
user = "root"
key = "ssh-rsa changeme"

#
# User
#
[[customizations.user]]
name = "admin"
description = "Admin User"
#password = "$6$x..."
key = "ssh-rsa changeme"
home = "/home/admin"
shell = "/bin/bash"
groups = ["wheel"]
uid = 4444
