---
# Tasks
rhel_image_do_setup: true
rhel_image_do_build: true
rhel_image_do_cleanup: true
rhel_image_do_uninstall: false

# Setup
rhel_image_update_host: false
rhel_image_create_user: false
rhel_image_builder_user: image-builder
rhel_image_reboot_host: false

# Blueprint
rhel_image_git_remote_repo: file:///tmp/rhel-image-blueprints.git
rhel_image_git_repo_checkout: master
rhel_image_local_repo_path: /tmp/blueprint-repo

# Build
rhel_image_blueprint: base-image
# This is on the build host
rhel_image_download_dir: /tmp/images
rhel_image_build_remove: true

# Image - only define needed options
rhel_image_output_type: qcow2
rhel_image_size_kb:
rhel_image_ostree_ref:
rhel_image_ostree_parent:
rhel_image_ostree_url:

# Fetch from build host
rhel_image_fetch_image: false
# This is where playbook runs
rhel_image_fetch_directory: /tmp
rhel_image_remote_delete: false
