---
- name: Install Image Builder
  yum:
    name:
      - composer-cli
      - git-core
      - osbuild-composer
      - tar
    state: present
  register: builder_packages

- name: Update all packages
  yum:
    name: '*'
    update_cache: true
    state: latest
  register: package_update
  when: rhel_image_update_host

- name: Enable Image Builder
  service:
    name: osbuild-composer.socket
    enabled: true
    state: started
  register: builder_socket

- name: Create user for building images
  user:
    name: "{{ rhel_image_builder_user }}"
    groups: weldr
    append: true
  register: user_create
  when: rhel_image_create_user

- name: Reboot system
  reboot:
  when:
    - rhel_image_reboot_host | bool
    - builder_packages is changed or
      package_update is changed or
      builder_socket is changed or
      user_create is changed
