---
- name: Uninstall Image Builder
  yum:
    name:
      - 'osbuild*'
      - weldr-client
    autoremove: true
    cacheonly: true
    state: absent
  register: builder_packages

- name: Remove Image Builder data directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/cache/osbuild-composer
    - /var/cache/osbuild-worker
    - /var/lib/osbuild-composer
  register: data_directories

- name: Get list of osbuilder temporary directories
  find:
    paths:
      - /tmp
      - /var/tmp
    patterns: 'dnf-_osbuild-composer*,tmp*'
    file_type: directory
    recurse: false
  register: temp_directories

- name: Delete osbuilder temporary directories
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ temp_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.pw_name == '_osbuild-composer'

- name: Reboot system
  reboot:
  when:
    - rhel_image_reboot_host | bool
    - builder_packages is changed or
      data_directories is changed
