---
- name: Uninstall Image Builder
  yum:
    name:
      - 'osbuild*'
      - weldr-client
    autoremove: true
    cacheonly: true
    state: absent
  register: builder_packages

- name: Remove Image Builder data directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/cache/osbuild-composer
    - /var/cache/osbuild-worker
    - /var/lib/osbuild-composer
  register: data_directories

- name: Reboot system
  reboot:
  when:
    - rhel_image_reboot_host | bool
    - builder_packages is changed or
      data_directories is changed
